[2023-12-16T13:18:22.662+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:13:11.674016+00:00 [queued]>
[2023-12-16T13:18:22.668+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:13:11.674016+00:00 [queued]>
[2023-12-16T13:18:22.668+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-16T13:18:22.688+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-16 08:13:11.674016+00:00
[2023-12-16T13:18:22.692+0500] {standard_task_runner.py:57} INFO - Started process 9897 to run task
[2023-12-16T13:18:22.695+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'transform', 'manual__2023-12-16T08:13:11.674016+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpp7z_j9zn']
[2023-12-16T13:18:22.695+0500] {standard_task_runner.py:85} INFO - Job 26: Subtask transform
[2023-12-16T13:18:22.739+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.transform manual__2023-12-16T08:13:11.674016+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T13:18:22.798+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T08:13:11.674016+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T08:13:11.674016+00:00'
[2023-12-16T13:18:22.799+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/sourav/airflow/dags/etl_dag.py", line 21, in transform_data
    data_dict = json.loads(data)  # Deserialize the JSON string into a dictionary
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2023-12-16T13:18:22.803+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_json_dag, task_id=transform, execution_date=20231216T081311, start_date=20231216T081822, end_date=20231216T081822
[2023-12-16T13:18:22.819+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task transform (Expecting property name enclosed in double quotes: line 1 column 2 (char 1); 9897)
[2023-12-16T13:18:22.828+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T13:18:22.844+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
