[2023-12-16T13:01:20.909+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:01:12.733230+00:00 [queued]>
[2023-12-16T13:01:20.915+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:01:12.733230+00:00 [queued]>
[2023-12-16T13:01:20.915+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T13:01:20.934+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-16 08:01:12.733230+00:00
[2023-12-16T13:01:20.936+0500] {standard_task_runner.py:57} INFO - Started process 8844 to run task
[2023-12-16T13:01:20.940+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'transform', 'manual__2023-12-16T08:01:12.733230+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpil18o0xa']
[2023-12-16T13:01:20.941+0500] {standard_task_runner.py:85} INFO - Job 11: Subtask transform
[2023-12-16T13:01:20.985+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.transform manual__2023-12-16T08:01:12.733230+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T13:01:21.053+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T08:01:12.733230+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T08:01:12.733230+00:00'
[2023-12-16T13:01:21.055+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/sourav/airflow/dags/etl_dag.py", line 18, in transform_data
    data_dict = json.loads(data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2023-12-16T13:01:21.058+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=transform, execution_date=20231216T080112, start_date=20231216T080120, end_date=20231216T080121
[2023-12-16T13:01:21.074+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task transform (Expecting property name enclosed in double quotes: line 1 column 2 (char 1); 8844)
[2023-12-16T13:01:21.112+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T13:01:21.129+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
