[2023-12-16T13:15:02.294+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:14:54.104061+00:00 [queued]>
[2023-12-16T13:15:02.300+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T08:14:54.104061+00:00 [queued]>
[2023-12-16T13:15:02.300+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T13:15:02.320+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-16 08:14:54.104061+00:00
[2023-12-16T13:15:02.322+0500] {standard_task_runner.py:57} INFO - Started process 9690 to run task
[2023-12-16T13:15:02.327+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'transform', 'manual__2023-12-16T08:14:54.104061+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp7o2rppq4']
[2023-12-16T13:15:02.328+0500] {standard_task_runner.py:85} INFO - Job 21: Subtask transform
[2023-12-16T13:15:02.379+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.transform manual__2023-12-16T08:14:54.104061+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T13:15:02.458+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T08:14:54.104061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T08:14:54.104061+00:00'
[2023-12-16T13:15:02.460+0500] {etl_dag.py:21} INFO - Data received in transform_data: {"size": 1, "parse_time_nanoseconds": 20642, "object_or_array": "object", "validate": true, "empty": false}
[2023-12-16T13:15:02.460+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/sourav/airflow/dags/etl_dag.py", line 23, in transform_data
    data['new_field'] = 'example_value'
TypeError: 'str' object does not support item assignment
[2023-12-16T13:15:02.464+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=transform, execution_date=20231216T081454, start_date=20231216T081502, end_date=20231216T081502
[2023-12-16T13:15:02.480+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task transform ('str' object does not support item assignment; 9690)
[2023-12-16T13:15:02.498+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T13:15:02.515+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
