[2023-12-16T14:00:15.848+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.dvc_push manual__2023-12-16T08:54:54.832273+00:00 [queued]>
[2023-12-16T14:00:15.852+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.dvc_push manual__2023-12-16T08:54:54.832273+00:00 [queued]>
[2023-12-16T14:00:15.853+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-16T14:00:15.874+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dvc_push> on 2023-12-16 08:54:54.832273+00:00
[2023-12-16T14:00:15.876+0500] {standard_task_runner.py:57} INFO - Started process 20213 to run task
[2023-12-16T14:00:15.880+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'dvc_push', 'manual__2023-12-16T08:54:54.832273+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmprxih16b4']
[2023-12-16T14:00:15.881+0500] {standard_task_runner.py:85} INFO - Job 35: Subtask dvc_push
[2023-12-16T14:00:15.928+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.dvc_push manual__2023-12-16T08:54:54.832273+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T14:00:15.976+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='dvc_push' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T08:54:54.832273+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T08:54:54.832273+00:00'
[2023-12-16T14:00:15.982+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T14:00:15.983+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && dvc push']
[2023-12-16T14:00:15.988+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T14:00:16.389+0500] {subprocess.py:93} INFO - ERROR: failed to push data to the cloud - config file error: no remote specified in /home/sourav/airflow. Create a default remote with
[2023-12-16T14:00:16.389+0500] {subprocess.py:93} INFO -     dvc remote add -d <remote name> <remote url>
[2023-12-16T14:00:16.534+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-16T14:00:16.540+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-16T14:00:16.542+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_json_dag, task_id=dvc_push, execution_date=20231216T085454, start_date=20231216T090015, end_date=20231216T090016
[2023-12-16T14:00:16.585+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task dvc_push (Bash command failed. The command returned a non-zero exit code 1.; 20213)
[2023-12-16T14:00:16.615+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T14:00:16.631+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
