[2023-12-16T15:22:10.268+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:21:49.845151+00:00 [queued]>
[2023-12-16T15:22:10.274+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:21:49.845151+00:00 [queued]>
[2023-12-16T15:22:10.274+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T15:22:10.290+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): git_push> on 2023-12-16 10:21:49.845151+00:00
[2023-12-16T15:22:10.293+0500] {standard_task_runner.py:57} INFO - Started process 44284 to run task
[2023-12-16T15:22:10.297+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'git_push', 'manual__2023-12-16T10:21:49.845151+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpn8t7w1f8']
[2023-12-16T15:22:10.297+0500] {standard_task_runner.py:85} INFO - Job 74: Subtask git_push
[2023-12-16T15:22:10.334+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:21:49.845151+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T15:22:10.395+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='git_push' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T10:21:49.845151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T10:21:49.845151+00:00'
[2023-12-16T15:22:10.399+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T15:22:10.400+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && git push origin new']
[2023-12-16T15:22:10.404+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T15:22:12.244+0500] {subprocess.py:93} INFO - git@github.com: Permission denied (publickey).
[2023-12-16T15:22:12.245+0500] {subprocess.py:93} INFO - fatal: Could not read from remote repository.
[2023-12-16T15:22:12.245+0500] {subprocess.py:93} INFO - 
[2023-12-16T15:22:12.245+0500] {subprocess.py:93} INFO - Please make sure you have the correct access rights
[2023-12-16T15:22:12.245+0500] {subprocess.py:93} INFO - and the repository exists.
[2023-12-16T15:22:12.245+0500] {subprocess.py:97} INFO - Command exited with return code 128
[2023-12-16T15:22:12.250+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2023-12-16T15:22:12.252+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=git_push, execution_date=20231216T102149, start_date=20231216T102210, end_date=20231216T102212
[2023-12-16T15:22:12.270+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task git_push (Bash command failed. The command returned a non-zero exit code 128.; 44284)
[2023-12-16T15:22:12.285+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T15:22:12.297+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
