[2023-12-16T12:58:50.204+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T07:58:42.094998+00:00 [queued]>
[2023-12-16T12:58:50.210+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.transform manual__2023-12-16T07:58:42.094998+00:00 [queued]>
[2023-12-16T12:58:50.210+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-16T12:58:50.229+0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-16 07:58:42.094998+00:00
[2023-12-16T12:58:50.232+0500] {standard_task_runner.py:57} INFO - Started process 8690 to run task
[2023-12-16T12:58:50.236+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'transform', 'manual__2023-12-16T07:58:42.094998+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpz6ockjjf']
[2023-12-16T12:58:50.237+0500] {standard_task_runner.py:85} INFO - Job 8: Subtask transform
[2023-12-16T12:58:50.278+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.transform manual__2023-12-16T07:58:42.094998+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T12:58:50.348+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T07:58:42.094998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T07:58:42.094998+00:00'
[2023-12-16T12:58:50.349+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/sourav/airflow/dags/etl_dag.py", line 19, in transform_data
    data['new_field'] = 'example_value'
TypeError: 'str' object does not support item assignment
[2023-12-16T12:58:50.353+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_json_dag, task_id=transform, execution_date=20231216T075842, start_date=20231216T075850, end_date=20231216T075850
[2023-12-16T12:58:50.368+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task transform ('str' object does not support item assignment; 8690)
[2023-12-16T12:58:50.409+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T12:58:50.426+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
