[2023-12-16T14:56:30.002+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:51:05.689282+00:00 [queued]>
[2023-12-16T14:56:30.007+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:51:05.689282+00:00 [queued]>
[2023-12-16T14:56:30.007+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-16T14:56:30.028+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): git_push> on 2023-12-16 09:51:05.689282+00:00
[2023-12-16T14:56:30.030+0500] {standard_task_runner.py:57} INFO - Started process 36506 to run task
[2023-12-16T14:56:30.035+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'git_push', 'manual__2023-12-16T09:51:05.689282+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp330_x98p']
[2023-12-16T14:56:30.036+0500] {standard_task_runner.py:85} INFO - Job 59: Subtask git_push
[2023-12-16T14:56:30.074+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.git_push manual__2023-12-16T09:51:05.689282+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T14:56:30.124+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='git_push' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T09:51:05.689282+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T09:51:05.689282+00:00'
[2023-12-16T14:56:30.130+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T14:56:30.131+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && git push']
[2023-12-16T14:56:30.135+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T14:56:31.976+0500] {subprocess.py:93} INFO - git@github.com: Permission denied (publickey).
[2023-12-16T14:56:31.976+0500] {subprocess.py:93} INFO - fatal: Could not read from remote repository.
[2023-12-16T14:56:31.977+0500] {subprocess.py:93} INFO - 
[2023-12-16T14:56:31.977+0500] {subprocess.py:93} INFO - Please make sure you have the correct access rights
[2023-12-16T14:56:31.977+0500] {subprocess.py:93} INFO - and the repository exists.
[2023-12-16T14:56:31.977+0500] {subprocess.py:97} INFO - Command exited with return code 128
[2023-12-16T14:56:31.984+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2023-12-16T14:56:31.987+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_json_dag, task_id=git_push, execution_date=20231216T095105, start_date=20231216T095630, end_date=20231216T095631
[2023-12-16T14:56:32.038+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task git_push (Bash command failed. The command returned a non-zero exit code 128.; 36506)
[2023-12-16T14:56:32.062+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T14:56:32.073+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
