[2023-12-16T15:13:57.222+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:08:31.283565+00:00 [queued]>
[2023-12-16T15:13:57.227+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:08:31.283565+00:00 [queued]>
[2023-12-16T15:13:57.227+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-16T15:13:57.246+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): git_push> on 2023-12-16 10:08:31.283565+00:00
[2023-12-16T15:13:57.248+0500] {standard_task_runner.py:57} INFO - Started process 41925 to run task
[2023-12-16T15:13:57.251+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_json_dag', 'git_push', 'manual__2023-12-16T10:08:31.283565+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxudsz1c1']
[2023-12-16T15:13:57.251+0500] {standard_task_runner.py:85} INFO - Job 67: Subtask git_push
[2023-12-16T15:13:57.288+0500] {task_command.py:416} INFO - Running <TaskInstance: etl_json_dag.git_push manual__2023-12-16T10:08:31.283565+00:00 [running]> on host DESKTOP-32G5QSE.
[2023-12-16T15:13:57.335+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_json_dag' AIRFLOW_CTX_TASK_ID='git_push' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T10:08:31.283565+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T10:08:31.283565+00:00'
[2023-12-16T15:13:57.340+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-16T15:13:57.341+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/sourav/airflow && git push']
[2023-12-16T15:13:57.346+0500] {subprocess.py:86} INFO - Output:
[2023-12-16T15:13:59.163+0500] {subprocess.py:93} INFO - git@github.com: Permission denied (publickey).
[2023-12-16T15:13:59.164+0500] {subprocess.py:93} INFO - fatal: Could not read from remote repository.
[2023-12-16T15:13:59.164+0500] {subprocess.py:93} INFO - 
[2023-12-16T15:13:59.164+0500] {subprocess.py:93} INFO - Please make sure you have the correct access rights
[2023-12-16T15:13:59.164+0500] {subprocess.py:93} INFO - and the repository exists.
[2023-12-16T15:13:59.164+0500] {subprocess.py:97} INFO - Command exited with return code 128
[2023-12-16T15:13:59.170+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sourav/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 128.
[2023-12-16T15:13:59.172+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_json_dag, task_id=git_push, execution_date=20231216T100831, start_date=20231216T101357, end_date=20231216T101359
[2023-12-16T15:13:59.206+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task git_push (Bash command failed. The command returned a non-zero exit code 128.; 41925)
[2023-12-16T15:13:59.239+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-16T15:13:59.252+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
